### ISSUE TITLE
Disclosure

### ISSUE THREAD

**Issue by dancompton** [qapital/android-test-task#4]
You're leaking non-obfuscated source-code on app.qapital.com and you're allowing anyone to download and install qapital purple with debugger via signing up on app-staging and my-staging :)

I post this here because Zendesk has stopped responding to my inquiries and wouldn't respond about responsible disclosure.

Also, if you could unlock my account and get zendesk to delete the PII they requested (licence etc) in exchange for unlocking my account that would be great.  I provided all requested data and the account remains locked.  I call this "bullying"

**Comment by erimag** [comment]
Hi Dan,

I apologize for the unhelpful response and thank you for the information. We are taking action and I will make sure we respond to you directly in a separate channel.

Erik Akterin
CTO, Qapital
